FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends build-essential&& apt-get install -y wget

# install R 4.2.3
RUN apt update -qq

RUN apt install -y --no-install-recommends software-properties-common dirmngr

RUN wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc

RUN add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"

RUN apt install -y --no-install-recommends r-base

# install Python 3.10.4
RUN add-apt-repository ppa:deadsnakes/ppa && apt-get update
RUN apt-get install -y  python3.10

RUN apt install python3.10 python3-venv python3.10-venv python3-dev -y
RUN python3.10 -m venv myvenv

ENV PATH=/myvenv/bin:$PATH
RUN python3 -V

RUN apt-get install python3-pip -y
RUN python3 -m pip install --upgrade pip

EXPOSE 8501
WORKDIR /app

ADD requirements.txt .
ADD requirements.r .
ADD website.py .
ADD pic1_10_2.r .
ADD pic2_10.r .
ADD proteinGroups_HsinYuan_Rat.txt .

# installing python libraries
RUN pip3 install -r requirements.txt

RUN apt-get update && apt-get upgrade
RUN apt-get install -y r-base-core r-base-dev libcurl4-openssl-dev libssl-dev
RUN apt-get update && apt-get upgrade
RUN apt-get install -y libcairo2-dev libxt-dev libnetcdf-dev libgdal-dev libnlopt-dev
RUN apt install -y cmake

# installing r libraries
RUN Rscript requirements.r

CMD streamlit run website.py