FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends build-essential&& apt-get install -y wget

# install R 4.3.1
RUN apt update -qq

RUN apt install -y --no-install-recommends software-properties-common dirmngr

RUN wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc

RUN add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"

RUN apt install -y --no-install-recommends r-base

# install Python 3.10.4
RUN apt update && apt install zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev libbz2-dev pkg-config -y
RUN wget https://www.python.org/ftp/python/3.10.4/Python-3.10.4.tgz
RUN tar -xf Python-3.10.*.tgz
RUN cd Python-3.10.4/
RUN ./configure --enable-optimizations
RUN make -j $(nproc)
RUN make altinstall
RUN apt install python3-venv python3-dev python3-pip -y
RUN python3.10 -m venv myvenv

ENV PATH=/myvenv/bin:$PATH
RUN python3 -V

RUN apt-get install python3-pip -y
RUN python3 -m pip install --upgrade pip

EXPOSE 8501
WORKDIR /app

RUN mkdir -p /app/file
ADD requirements.txt .
ADD requirements.r .
ADD website.py .
ADD dep1_to_1_5.r .
ADD dep2_1_6_to_1_8_1_10.r .
ADD dep3_1_9.r .
ADD dose1_config.r .
ADD dose2_plot.r .
ADD dose3_plot2_8.r .
ADD normalize_function.r .
ADD uniprotAPI.r .
ADD proteinGroups_HsinYuan_Rat.txt .

# installing python libraries
RUN pip3 install -r requirements.txt

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y r-base-core r-base-dev libcurl4-openssl-dev libssl-dev
RUN apt-get update && apt-get upgrade
RUN apt-get install -y libcairo2-dev libxt-dev libnetcdf-dev libgdal-dev libnlopt-dev
RUN apt install -y cmake
RUN apt-get install -y default-jdk
# installing r libraries
RUN Rscript requirements.r

CMD streamlit run website.py