library(BiocManager)
BiocManager::install("biomaRt")
BiocManager::install("org.Hs.eg.db")
BiocManager::install(c("vitkl/orthologsBioMART"), dependencies=T)
BiocManager::install("DOSE")
BiocManager::install("enrichplot")
BiocManager::install("clusterProfiler")
BiocManager::install("ggplot2")
BiocManager::install("cowplot")
BiocManager::install("MSnbase")
BiocManager::install("SummarizedExperiment")
BiocManager::install("MatrixGenerics")
BiocManager::install("GenomicRanges")
BiocManager::install("DelayedArray")
install.packages("ggnewscale")
install.packages("ggupset")
install.packages("ggridges")
install.packages("europepmc")
install.packages('mvtnorm')
install.packages('gmm')
install.packages('norm')
install.packages('shinydashboard')
install.packages("DT")
install.packages("matrixStats")

